services:
  analysis-env:
    image: angelayandrofski/dockerfile-practice:latest
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/work
    environment:
      PASSWORD: "password"
      DISABLE_AUTH: true 